<?php
namespace app\admin\controller;
use app\admin\controller\Common;
use think\Paginator;


class AdminBase extends Common
{
   public function _initialize()
   {
       parent::_initialize(); // TODO: Change the autogenerated stub
       if(!session('admin_id')){
           $this->redirect(url('admin/login/login'));
       }
       $this->curModule = strtolower(request()->module());
       $this->curController = strtolower(request()->controller());
       $this->curAction = strtolower(request()->action());
        if(!check_auth($this->curModule,$this->curController,$this->curAction)){
            $this->error('没有此权限');
        }
        $this->public_assign();
   }
   public function public_assign(){

       /*获取当前链接的顶级id*/
       $tmp = topId_leftId($this->curModule,$this->curController,$this->curAction);

        $this->assign('topid',$tmp['topid']);
       $this->assign('leftid',$tmp['leftid']);

       /*获取顶部导航*/
       $topNav = db_base('menu')->where(['parentid'=>0,'show'=>1])->select();
       foreach($topNav as $k=>$v){
           $topNav[$k]['url'] = url($v['m'].'/'.$v['c']."/".$v['a']);
       }
       check_auth_menu($topNav);
       $this->assign('topNav',$topNav);
       /*获取左边导航*/
       $id =  db_base('menu')->where(['parentid'=>0,'m'=> $this->curModule])->value('id');
       $leftNav = left_menu($id);

       check_auth_menu($leftNav);
       $this->assign('leftNav',$leftNav);
       $this->assign('curModule',$this->curModule);
       $this->assign('curController',$this->curController);
       $this->assign('curAction',$this->curAction);
   }



}
