<?php
namespace app\admin\controller;
use think\Controller;
use think\Request;


class Common extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }


    public function error($msg = '', $url = null, $data = '', $wait = 3, array $header = []){
        if(request()->isAjax()){
            $error = array(
                'msg'=>$msg,
                'status'=>0,
                'url'=>$url,
                'data'=>$data
            );
            die(json_encode($error));
        }else{
            parent::error($msg , $url, $data, $wait, $header);
        }
    }
    public function success($msg = '', $url = null, $data = '', $wait = 3, array $header = []){
        if(request()->isAjax()){
            $error = array(
                'msg'=>$msg,
                'status'=>1,
                'url'=>$url,
                'data'=>$data
            );
            die(json_encode($error));
        }else{
            parent::success($msg , $url, $data, $wait, $header);
        }
    }
}
